public with sharing class CarbonInterfaceConstants {

    




    public static class STATUS_CODES {

        public static final Integer OK {
            get {
                return 200;
            } set;
        }

        public static final Integer OBJECT_CREATED {
            get {
                return 201;
            }
        }

        public static final Integer BAD_REQUEST {
            get {
                return 400;
            } set;
        }

        public static final Integer UNAUTHORIZED {
            get {
                return 400;
            } set;
        }

        public static final Integer INTERNAL_SERVER_ERROR {
            get {
                return 500;
            } set;
        }

    }


}